# Generated by Django 4.2.19 on 2025-04-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_image_options_post_banner_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Praxia', max_length=255, verbose_name='Autor'),
        ),
    ]
