# Generated by Django 4.2.19 on 2025-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_pdf_file_alter_post_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_file',
        ),
        migrations.AddField(
            model_name='post',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='PDF URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Video URL'),
        ),
    ]
