# Generated by Django 4.2.19 on 2025-04-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_pdf_file_remove_post_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='¿Está activo? Si no está activo no se mostrará en la web', verbose_name='¿Está activo?'),
        ),
    ]
