# Generated by Django 4.2.16 on 2024-12-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historial",
            old_name="fecha",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="documento",
            name="fecha_carga",
        ),
        migrations.RemoveField(
            model_name="historial",
            name="acciones",
        ),
        migrations.RemoveField(
            model_name="historial",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="historial",
            name="usuario",
        ),
        migrations.AddField(
            model_name="historial",
            name="momento",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot_app.momento",
            ),
        ),
        migrations.AddField(
            model_name="historial",
            name="respuesta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot_app.respuesta",
            ),
        ),
        migrations.AddField(
            model_name="historial",
            name="submomento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot_app.submomento",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="momento",
            name="programa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot_app.programa"
            ),
        ),
        migrations.AlterField(
            model_name="programa",
            name="tipo_lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot_app.tipolead"
            ),
        ),
        migrations.AlterField(
            model_name="respuesta",
            name="submomento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot_app.submomento"
            ),
        ),
        migrations.AlterField(
            model_name="submomento",
            name="momento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot_app.momento"
            ),
        ),
        migrations.AlterField(
            model_name="submomento",
            name="programa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot_app.programa",
            ),
        ),
        migrations.AlterField(
            model_name="submomento",
            name="tipo_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot_app.tipolead",
            ),
        ),
    ]
