# Generated by Django 5.1.5 on 2025-01-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_rename_fecha_historial_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
