# Generated by Django 5.1.5 on 2025-02-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_delete_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momento',
            name='respuesta_momento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
