# Generated by Django 5.1.5 on 2025-02-06 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0005_alter_documento_id_alter_momento_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momento',
            name='respuesta_momento',
        ),
        migrations.RemoveField(
            model_name='submomento',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='submomento',
            name='tipo_lead',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='titulo',
            field=models.CharField(default='Respuesta', max_length=200),
        ),
        migrations.AlterField(
            model_name='documento',
            name='palabras_clave',
            field=models.TextField(help_text='Palabras clave separadas por coma'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='prioridad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
