# Generated by Django 5.1.5 on 2025-02-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0006_remove_momento_respuesta_momento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='palabras_clave',
            field=models.TextField(blank=True, help_text='Palabras clave separadas por coma', null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='submomento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.submomento'),
        ),
    ]
