# Generated by Django 5.1.5 on 2025-02-13 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0007_delete_documento_respuesta_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('palabras_clave', models.TextField(help_text='Palabras clave separadas por coma')),
            ],
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='palabras_clave',
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='submomento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.submomento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.documento'),
        ),
    ]
