# Generated by Django 5.1.5 on 2025-02-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0008_documento_remove_respuesta_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
