# Generated by Django 4.2.19 on 2025-02-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0009_alter_respuesta_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_app.documento'),
        ),
    ]
