# Generated by Django 4.2.19 on 2025-02-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0010_alter_respuesta_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='palabras_clave_valores',
            field=models.TextField(default=''),
        ),
    ]
