# Generated by Django 4.2.19 on 2025-02-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0011_documento_palabras_clave_valores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='palabras_clave_valores',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
