# Generated by Django 4.2.19 on 2025-02-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0012_alter_documento_palabras_clave_valores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='palabras_clave_valores',
        ),
    ]
