# Generated by Django 4.2.19 on 2025-03-05 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0013_remove_documento_palabras_clave_valores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_app.documento'),
        ),
    ]
