# Generated by Django 4.2.19 on 2025-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0016_alter_respuesta_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
